# Generated by Django 4.2.20 on 2025-04-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyticker",
            name="date",
            field=models.DateField(),
        ),
    ]
