# Generated by Django 4.2.20 on 2025-04-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_dailyticker_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyticker",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
