# Generated by Django 4.2.20 on 2025-04-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_dailyticker_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="predicted",
            field=models.BooleanField(default=False),
        ),
    ]
