# Generated by Django 4.2.20 on 2025-04-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_userprofile_predicted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyticker",
            name="date",
            field=models.DateField(),
        ),
    ]
