# Generated by Django 4.2.20 on 2025-04-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_dailyticker_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyticker",
            name="prev_symbol",
            field=models.CharField(default=None, max_length=10),
        ),
    ]
