# Generated by Django 4.2.20 on 2025-04-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_dailyticker_prev_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyticker",
            name="prev_symbol",
            field=models.CharField(default="", max_length=10),
        ),
    ]
