# Generated by Django 4.2.20 on 2025-04-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_dailyticker_prev_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyprediction",
            name="ticker",
        ),
        migrations.AddField(
            model_name="dailyprediction",
            name="symbol",
            field=models.CharField(default="", max_length=10),
        ),
    ]
