# Generated by Django 4.2.20 on 2025-04-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_previousprediction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="previousprediction",
            name="ticker",
            field=models.CharField(default="", max_length=10),
        ),
    ]
